"""Turn benchmark JSON results into a markdown report."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def load_all(results_dir: Path) -> list[dict]:
    summaries = []
    for file in sorted(results_dir.glob("*.json")):
        try:
            summaries.append(json.loads(file.read_text()))
        except Exception:
            continue
    return summaries


def render(summaries: list[dict]) -> str:
    if not summaries:
        return "# Benchmark report\n\nNo results found.\n"

    latest: dict[str, dict] = {}
    for summary in summaries:
        key = summary.get("label", "unknown")
        if key not in latest or summary["timestamp"] > latest[key]["timestamp"]:
            latest[key] = summary

    order = ["full", "no-memory", "no-planner", "no-tools", "no-reflection"]
    rows = [latest[label] for label in order if label in latest]
    for label, summary in latest.items():
        if summary not in rows:
            rows.append(summary)

    lines: list[str] = []
    lines.append("# Benchmark report\n")
    lines.append(f"Ablations ({len(rows)}), most recent per label.\n")

    lines.append("## Summary\n")
    lines.append("| Label | Tasks | Overall score | Success | Tool precision | Tool recall | Context utility | Reflection ROI | Mean latency |")
    lines.append("|---|---:|---:|---:|---:|---:|---:|---:|---:|")
    for summary in rows:
        lines.append(
            f"| `{summary['label']}` "
            f"| {summary['task_count']} "
            f"| {summary['overall_score']:.3f} "
            f"| {summary['success_rate']:.1%} "
            f"| {_fmt_rate(summary.get('tool_precision'))} "
            f"| {_fmt_rate(summary.get('tool_recall'))} "
            f"| {_fmt_rate(summary.get('context_utility_rate'))} "
            f"| {_fmt_float(summary.get('reflection_roi'))} "
            f"| {summary['mean_latency_ms']} ms |"
        )

    full = latest.get("full")
    if full:
        lines.append("\n## Ablation deltas (vs. `full`)\n")
        lines.append("| Label | Δ overall score | Δ success rate |")
        lines.append("|---|---:|---:|")
        for summary in rows:
            if summary["label"] == "full":
                continue
            dscore = summary["overall_score"] - full["overall_score"]
            drate = summary["success_rate"] - full["success_rate"]
            lines.append(f"| `{summary['label']}` | {dscore:+.3f} | {drate:+.1%} |")

        lines.append("\n## Per-category scores (`full` run)\n")
        lines.append("| Category | n | Avg score |")
        lines.append("|---|---:|---:|")
        for cat, info in full.get("by_category", {}).items():
            lines.append(f"| {cat} | {info['n']} | {info['avg_score']:.3f} |")

        if full.get("by_slice"):
            lines.append("\n## Slice scores (`full` run)\n")
            lines.append("| Slice | n | Avg score |")
            lines.append("|---|---:|---:|")
            for slice_name, info in full.get("by_slice", {}).items():
                lines.append(f"| {slice_name} | {info['n']} | {info['avg_score']:.3f} |")

    lines.append("\n## Flags per run\n")
    lines.append("| Label | memory | planner | tools | reflection | otel |")
    lines.append("|---|:-:|:-:|:-:|:-:|:-:|")
    for summary in rows:
        flags = summary.get("flags", {})
        lines.append(
            f"| `{summary['label']}` "
            f"| {'on' if flags.get('memory') else 'off'} "
            f"| {'on' if flags.get('planner') else 'off'} "
            f"| {'on' if flags.get('tools') else 'off'} "
            f"| {'on' if flags.get('reflection') else 'off'} "
            f"| {'on' if flags.get('otel') else 'off'} |"
        )

    lines.append("\n---")
    lines.append("\n_Generated by `python -m bench.report`._")
    return "\n".join(lines) + "\n"


def _fmt_rate(value: float | None) -> str:
    return "n/a" if value is None else f"{value:.1%}"


def _fmt_float(value: float | None) -> str:
    return "n/a" if value is None else f"{value:.3f}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default=str(ROOT / "bench" / "results"))
    ap.add_argument("--out", default=str(ROOT / "bench" / "results" / "REPORT.md"))
    args = ap.parse_args()

    results_dir = Path(args.results)
    summaries = load_all(results_dir)
    md = render(summaries)
    Path(args.out).write_text(md)
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
